version: "3.8"
services:
  template-web:
    container_name: template-web
    build:
      context: web/
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - "3000:3000"
  template-server:
    container_name: template-server
    build:
      context: server/
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
